# Generated by Django 3.0.8 on 2020-07-16 19:14

from django.db import migrations


def forwards(apps, schema_editor):
    Provider = apps.get_model("base", "Provider")

    Provider.objects.create(name="telegram")


def backwards(apps, schema_editor):
    Provider = apps.get_model("base", "Provider")

    Provider.objects.filter(name="telegram").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
