# Generated by Django 3.0.8 on 2020-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_add_telegram_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_name", models.CharField(max_length=255)),
                ("settings", models.CharField(max_length=255)),
                (
                    "provider",
                    models.ForeignKey(
                        db_column="provider_name",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.Provider",
                        verbose_name="Provider name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "db_table": "connections",
            },
        ),
        migrations.CreateModel(
            name="AsapSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.Connection"
                    ),
                ),
            ],
            options={
                "verbose_name": "ASAP schedule",
                "verbose_name_plural": "ASAP schedules",
                "db_table": "asap_schedules",
            },
        ),
    ]
